export const PRICES_GET_SEARCH = {
  SUCCESS: 'PRICES_GET_SEARCH_SUCCESS',
  LOADING: 'PRICES_GET_SEARCH_LOADING',
  ERROR: 'PRICES_GET_SEARCH_ERROR',
};

export const HOTELS_GET_LIST = {
  SUCCESS: 'HOTELS_GET_LIST_SUCCESS',
  LOADING: 'HOTELS_GET_LIST_LOADING',
  ERROR: 'HOTELS_GET_LIST_ERROR',
};

export const COUNTRIES = {
  SET_SEARCH_ID: 'SEARCH_ID',
}
