export const PRICES_START_SEARCH = {
  SUCCESS: 'PRICES_START_SEARCH_SUCCESS',
  LOADING: 'PRICES_START_SEARCH_LOADING',
  ERROR: 'PRICES_START_SEARCH_ERROR',
};

export const PRICES_GET_SEARCH = {
  SUCCESS: 'PRICES_GET_SEARCH_SUCCESS',
  LOADING: 'PRICES_GET_SEARCH_LOADING',
  ERROR: 'PRICES_GET_SEARCH_ERROR',
};
