export const PRICES_GET_SEARCH = {
  SUCCESS: 'PRICES_GET_SEARCH_SUCCESS',
  LOADING: 'PRICES_GET_SEARCH_LOADING',
  ERROR: 'PRICES_GET_SEARCH_ERROR',
};

export const PRICE_GET_BY_ID = {
  SUCCESS: 'PRICE_GET_BY_ID_SUCCESS',
  LOADING: 'PRICE_GET_BY_ID_LOADING',
  ERROR: 'PRICE_GET_BY_ID_ERROR',
};

export const HOTELS_GET_LIST = {
  SUCCESS: 'HOTELS_GET_LIST_SUCCESS',
  LOADING: 'HOTELS_GET_LIST_LOADING',
  ERROR: 'HOTELS_GET_LIST_ERROR',
};

export const HOTELS_GET_DETAILS_LIST = {
  SUCCESS: 'HOTELS_GET_DETAILS_LIST_SUCCESS',
  LOADING: 'HOTELS_GET_DETAILS_LIST_LOADING',
  ERROR: 'HOTELS_GET_DETAILS_LIST_ERROR',
};


export const COUNTRIES_GET_LIST = {
  SUCCESS: 'COUNTRIES_GET_LIST_SUCCESS',
  LOADING: 'COUNTRIES_GET_LIST_LOADING',
  ERROR: 'COUNTRIES_GET_LIST_ERROR',
};

export const COUNTRIES = {
  SET_SEARCH_ID: 'SEARCH_ID',
}
